version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - example.env
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      
  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - example.env
    volumes:
      - mydatabase:/var/lib/mysql

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=duko102003@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
      - ./data/certbot:/var/www/certbot
    depends_on:
      - myportfolio
      
volumes:
  mydatabase:
  nginx_secrets:
